### PR TITLE
Support async auto-service

### PR DESCRIPTION
**Pull request by joeeltgroth**

### CODE REVIEW

**Comment by mboldt** [comment]
Some thoughts/questions:
1. As-is, it looks like if the creation fails, it will wait for the 20-minute timeout. Could we check for the failure case too to avoid that? Or, alternatively, look for “not in pending state”.
2. How huge does `CF_TRACE` make the output?
3. If/when needed, we could make the timeout configurable…I agree with leaving it hardcoded for now.
4. Instead of `cf s`, we could do `cf service "$1"` and grep for the `^Status:` line. This saves from weird issues with multiple matches on the `grep "$1"` (unlikely, but you never know).

**Comment by joeeltgroth** [comment]
I will dig into #1 & #4.  I like the idea of using cf service to limit the potential amount of details coming back, and finding the states that indicate failure to avoid hitting the timeout.  #2: does CF_TRACE end up in output anywhere? I thought it just resulted in a boolean (or int) in "$?" ?

**Comment by joeeltgroth** [comment]
I have created a 2nd commit.  If looks good, we would 'squash and merge' I think.

**Comment by mboldt** [comment]
lgtm. If you've tested, feel free to squash and merge (or we can do together tomorrow).

**Pull request merged**
