### PR TITLE
Allow make plans on service plan form non-optional

### PR DESCRIPTION
**Pull request by alex-slynko**

### CODE REVIEW

**Comment by alex-slynko** [comment]
Hi @guidowb 
Could you please take a look on this and #150 #151

**Comment by mboldt** [comment]
For consistency, I'd prefer to have the input called `optional` instead of `required`. Does that work for you, @alex-slynko?

**Comment by alex-slynko** [comment]
@mboldt I am ok with that. Do you want me to do that?

**Comment by mboldt** [comment]
Fixed in 79cf2e1a16a14c4cbf869d4efd04725535df9f29. Thanks again, @alex-slynko!

**Pull request closed without merging**
