### PR TITLE
Add option to disable purging services before deletion

### PR DESCRIPTION
**Pull request by jhvhs**
Signed-off-by: Oleksandr Slynko oslynko@pivotal.io

### CODE REVIEW

**Comment by jhvhs** [comment]
Conflict resolved

**Comment by guidowb** [comment]
Sorry @jhvhs I created another conflict for you before I saw your pull requests today. If you are willing to resolve one more time I'll merge it before proceeding with my changes in this area.

Really appreciate your contributions!

**Comment by jhvhs** [comment]
Hi @guidowb,

We fixed the conflict.

**Comment by guidowb** [comment]
Thank you!

**Pull request merged**
